Operations of tensors using Pytorch

In [102]:
import torch

block_size = 8
batch_size = 4

In [3]:
with open('demo_text.txt', 'r', encoding = 'utf-8') as f:
    text = f.read()
print(text[:200])

chars = sorted(set(text))
print(chars)
print(len(chars))
print(len(text))
    

In the heart of a bustling city, people move with purpose, weaving stories into the fabric of daily life
The aroma of fresh coffee drifts from a nearby café, mingling with the distant hum of traffic a
['\n', ' ', ',', '.', ':', 'A', 'I', 'N', 'S', 'T', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'y', 'z', 'é']
35
1154


In [4]:
string_to_int = {ch:i for i,ch in enumerate(chars)}
int_to_string = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

# encoded_hello = encode('hello')
# decoded_hello = decode(encoded_hello, dtype = torch.long)
# print(decoded_hello)

data = torch.tensor(encode(text), dtype= torch.long)
print(data[:100])



tensor([ 6, 22,  1, 28, 17, 14,  1, 17, 14, 10, 26, 28,  1, 23, 15,  1, 10,  1,
        11, 29, 27, 28, 20, 18, 22, 16,  1, 12, 18, 28, 32,  2,  1, 24, 14, 23,
        24, 20, 14,  1, 21, 23, 30, 14,  1, 31, 18, 28, 17,  1, 24, 29, 26, 24,
        23, 27, 14,  2,  1, 31, 14, 10, 30, 18, 22, 16,  1, 27, 28, 23, 26, 18,
        14, 27,  1, 18, 22, 28, 23,  1, 28, 17, 14,  1, 15, 10, 11, 26, 18, 12,
         1, 23, 15,  1, 13, 10, 18, 20, 32,  1])


In [5]:
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]

In [6]:
block_size = 8

x= train_data[:block_size]
y = train_data[:block_size + 1]

for t in range(block_size):
    context = x[:t + 1]
    target = y[t]
    print("when input is:", context, "target is:", target)

when input is: tensor([6]) target is: tensor(6)
when input is: tensor([ 6, 22]) target is: tensor(22)
when input is: tensor([ 6, 22,  1]) target is: tensor(1)
when input is: tensor([ 6, 22,  1, 28]) target is: tensor(28)
when input is: tensor([ 6, 22,  1, 28, 17]) target is: tensor(17)
when input is: tensor([ 6, 22,  1, 28, 17, 14]) target is: tensor(14)
when input is: tensor([ 6, 22,  1, 28, 17, 14,  1]) target is: tensor(1)
when input is: tensor([ 6, 22,  1, 28, 17, 14,  1, 17]) target is: tensor(17)


In [7]:
randint = torch.randint(-100, 100, (10,))
print(randint)

tensor([ 77,  77,   4, -43,  93, -26, -38, -67, -53,  59])


In [8]:
tensor = torch.tensor([1, 2, 3, 4, 5])
print(tensor)

tensor([1, 2, 3, 4, 5])


In [9]:
zeros = torch.zeros((2, 3, 4))
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
ones = torch.ones((2, 3, 4))
print(ones)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [11]:
input = torch.randn((2, 3, 4))
input

tensor([[[-2.2074,  0.4338,  0.3849,  0.8459],
         [-0.4016, -0.6425, -0.0284,  0.5433],
         [ 0.0621,  0.4865,  1.6807,  1.2790]],

        [[-0.4162,  0.2513,  0.7131, -1.1940],
         [-1.0609,  0.5034, -0.5833,  0.6173],
         [ 0.8824, -2.4127,  0.1613, -1.2737]]])

In [19]:
input = torch.empty((2, 3, 4))
print(input)
print(input.size())


tensor([[[-5.6974e+22,  1.6577e-42,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 3, 4])


In [21]:
arange = torch.arange(0, 10, 2)
print(arange)
print(arange.size())

tensor([0, 2, 4, 6, 8])
torch.Size([5])


In [14]:
linspace = torch.linspace(0, 1, 5)
print(linspace)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [15]:
logspace = torch.logspace(start=0, end=1, steps=5, base=16)
print(logspace)

tensor([ 1.,  2.,  4.,  8., 16.])


In [16]:
eye = torch.eye(3, 3)
print(eye)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [26]:
input = torch.tensor([5,5,3])
print(input, input.dtype)

tensor([5, 5, 3]) torch.int64


In [27]:
input = torch.zeros((batch_size, block_size), dtype = torch.long)
print(input)

tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]])


In [58]:
x = torch.tensor([[2,3], [2,45], [35, 325]])
y = torch.tensor([[2,23,43], [113,35,24]])
z = torch.tensor([[2,3], [5,6], [8,9]])


In [59]:
x.shape

torch.Size([3, 2])

In [60]:
y.shape

torch.Size([2, 3])

In [61]:
print(torch.matmul(x, y))
print(x@y)

tensor([[  343,   151,   158],
        [ 5089,  1621,  1166],
        [36795, 12180,  9305]])
tensor([[  343,   151,   158],
        [ 5089,  1621,  1166],
        [36795, 12180,  9305]])


In [62]:
print(x.add(z))

tensor([[  4,   6],
        [  7,  51],
        [ 43, 334]])


In [67]:
print(x // z)

tensor([[ 1,  1],
        [ 0,  7],
        [ 4, 36]])


In [68]:
print(x.sub(z))

tensor([[  0,   0],
        [ -3,  39],
        [ 27, 316]])


In [94]:
x = torch.randint(3,20, (5,2,3,1), dtype= torch.long)
print(x[:1], x.shape)

tensor([[[[13],
          [ 5],
          [16]],

         [[ 8],
          [ 4],
          [19]]]]) torch.Size([5, 2, 3, 1])


In [100]:
# Option 1: Print a single element as a scalar
print(x[0, 0, 0, 0].item())

# Option 2: Print the entire tensor as a nested list
print(x.tolist())
print(x.view(-1, 3))  # Reshape to a 2D tensor with 3 columns

13
[[[[13], [5], [16]], [[8], [4], [19]]], [[[15], [8], [9]], [[10], [7], [14]]], [[[15], [9], [10]], [[4], [3], [11]]], [[[12], [15], [17]], [[3], [17], [12]]], [[[4], [15], [4]], [[4], [4], [8]]]]
tensor([[13,  5, 16],
        [ 8,  4, 19],
        [15,  8,  9],
        [10,  7, 14],
        [15,  9, 10],
        [ 4,  3, 11],
        [12, 15, 17],
        [ 3, 17, 12],
        [ 4, 15,  4],
        [ 4,  4,  8]])


In [101]:
print(x.size(), y.size(), z.size())

torch.Size([5, 2, 3, 1]) torch.Size([2, 3]) torch.Size([3, 2])


In [103]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cpu


In [105]:
x = torch.rand(batch_size, block_size).to(device)
print(x)

tensor([[0.3190, 0.5550, 0.1120, 0.5046, 0.8893, 0.6205, 0.5180, 0.0465],
        [0.3456, 0.5320, 0.8158, 0.2707, 0.6676, 0.2490, 0.0023, 0.5556],
        [0.7984, 0.4222, 0.6529, 0.8522, 0.9466, 0.7298, 0.8322, 0.9463],
        [0.2635, 0.1863, 0.8744, 0.4148, 0.8129, 0.1432, 0.6560, 0.1707]])


In [106]:
x = x.to('cpu')
x = x.to('cuda') if torch.cuda.is_available() else x
print(x)

tensor([[0.3190, 0.5550, 0.1120, 0.5046, 0.8893, 0.6205, 0.5180, 0.0465],
        [0.3456, 0.5320, 0.8158, 0.2707, 0.6676, 0.2490, 0.0023, 0.5556],
        [0.7984, 0.4222, 0.6529, 0.8522, 0.9466, 0.7298, 0.8322, 0.9463],
        [0.2635, 0.1863, 0.8744, 0.4148, 0.8129, 0.1432, 0.6560, 0.1707]])


In [108]:
x = torch.rand(2,2, device=device)
print(x)

tensor([[0.3795, 0.7909],
        [0.3132, 0.9437]])


Autograd (Automatic Differentiation for all operations on tensors, torch.autograd is an engine for computing the vector-jacobian product computes partial derivatives while applying chain rule.)

In [116]:
x = torch.randn(3, requires_grad=True)
y = x + 2
print(x.grad)
print(x.grad_fn)
print(y.grad_fn)

None
None


In [118]:
x= torch.randn(3, requires_grad=True)
y = x + 2
z = y * y * 3

mean = z.mean()
print(z, mean)
mean.backward() # backward pass to compute gradients -> backpropagation
print(x.grad) # dz/dx
print(x.grad_fn)
print(y.grad_fn)

tensor([17.1438, 26.6535,  0.4073], grad_fn=<MulBackward0>) tensor(14.7349, grad_fn=<MeanBackward0>)
tensor([4.7810, 5.9614, 0.7370])
None


Stop tensors from tracking history

In [127]:
# .requires_grad_(...) changes an existing flag in-place
a =torch.randn(2,2,)
b = (a*a).sum()
print(a.requires_grad)
print(b.grad_fn)

a.requires_grad_(True)
b = (a*a).sum()
print(a.requires_grad)
print(b.grad_fn)

False
None
True


In [128]:
# .detach(): get a new tensor iwth the same content but no  gradient computation:
a = torch.randn(2,2, requires_grad=True)
b = a.detach() # copy
print(a.requires_grad)
print(b.requires_grad)

True
False


In [130]:
# wrap in 'with torch.no_grad()'
a = torch.randn(2,2, requires_grad=True)
print(a.requires_grad)
with torch.no_grad():
    b = a ** 2
    print(b.requires_grad)

True
False


Gradient descent Autograd
Linear regression with Autograd package:
f(x) = W*x+b

In [133]:
X = torch.tensor([1,2,3,4,5,6,7,8], dtype=torch.float32)
Y = torch.tensor([2,4,6,8,10,12,14,16], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

# Model output
def forward(x):
    return w * x

# loss = MSE
def loss(y, y_pred):
    return ((y_pred - y) ** 2).mean()

X_test = 5.0

print(f'Prediction before training: f({X_test}) = {forward(X_test).item():.3f}')

Prediction before training: f(5.0) = 0.000


In [134]:
# Training

learning_rate = 0.01
n_epochs= 100

In [136]:
for epochs in range(n_epochs):
    y_pred = forward(X) # forward pass
    
    l = loss(Y, y_pred) # compute loss
    
    l.backward()  # compute gradients 
    
    with torch.no_grad():
        w -= learning_rate * w.grad # update weights
    w.grad.zero_()
    if epochs % 10 == 0: # print progress
        print(f'Epoch {epochs}, Loss: {l.item():.4f}, w: {w.item():.4f}')
print(f'Prediction after training: f({X_test}) = {forward(X_test).item():.3f}') # final prediction


Epoch 0, Loss: 0.0000, w: 2.0000
Epoch 10, Loss: 0.0000, w: 2.0000
Epoch 20, Loss: 0.0000, w: 2.0000
Epoch 30, Loss: 0.0000, w: 2.0000
Epoch 40, Loss: 0.0000, w: 2.0000
Epoch 50, Loss: 0.0000, w: 2.0000
Epoch 60, Loss: 0.0000, w: 2.0000
Epoch 70, Loss: 0.0000, w: 2.0000
Epoch 80, Loss: 0.0000, w: 2.0000
Epoch 90, Loss: 0.0000, w: 2.0000
Prediction after training: f(5.0) = 10.000


Model optimizers and Loss functions - A typical pytorch pipeline

1. Design Model (i/p, o/p, forward pass with different layers)
2. Construct loss and optimizers
3. Training loop:
        1. Forward propagation
        2. backward propagation
        3. weight update

In [137]:
import torch.nn as nn
import torch.optim as optim

x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
y = torch.tensor([[2, 3], [4, 5]], dtype=torch.float32)

n_sample, n_features = x.shape
print(n_sample, n_features)

X_test = torch.tensor([[5, 6]], dtype=torch.float32)

2 2


In [138]:
class LinearRegression(nn.Module):
    def __init__(self, n_features):
        super(LinearRegression, self).__init__()
        self.linear = nn.Linear(n_features, 1)  # Linear layer with n_features input and 1 output

    def forward(self, x):
        return self.linear(x)